### ISSUE TITLE
Top-level final state causes crash

### ISSUE THREAD

**Issue by nobrayner** [statelyai/xstate-python#45]
If one of the top-level states is a final state, the machine crashes when entering that state.

[Line 292](https://github.com/statelyai/xstate-python/blob/master/xstate/algorithm.py#L292) in enter_states assumes that a grandparent exists, when if it is a top-level state, there is no grandparent.

```
root -> Final state // No grandparent!
```

**Comment by nobrayner** [comment]
@davidkpiano Is this one just a simple if statement to check if the grandparent exists before trying to do anything with it?

**Comment by davidkpiano** [comment]
> @davidkpiano Is this one just a simple if statement to check if the grandparent exists before trying to do anything with it?

Yep; this is also a fault of the original algorithm:

```
            else:
                parent = s.parent
                grandparent = parent.parent
                internalQueue.enqueue(new Event("done.state." + parent.id, s.donedata))
                if isParallelState(grandparent):
                    if getChildStates(grandparent).every(isInFinalState):
                        internalQueue.enqueue(new Event("done.state." + grandparent.id))
```

There is no existence check on `grandparent` here either.
